services:
  db:
    build:
      context: sql/
      dockerfile: Dockerfile

  backend:
    build:
      context: python/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db