services:
  db:
    build:
      context: sql/
      dockerfile: Dockerfile
    volumes:
      - ./sql/data:/var/lib/mysql

  backend:
    build:
      context: python/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    
  fcm_messaging:
    build:
      context: python_fcm/
      dockerfile: Dockerfile
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
#Probando permisos
